baseURL = "/"
languageCode = "ja"
title = "Notation Co. JP"
theme = "stack"
defaultContentLanguage = "ja"
hasCJKLanguage = true
enableRobotsTXT = true

[minify]
  disableXML = true
  minifyOutput = true

[permalinks]
  post = "/p/:slug/"
  page = "/:slug/"

[params]
  mainSections = ["post"]
  featuredImageField = "image"
  rssFullContent = true

[params.footer]
  since = 2025
  customText = ""

[params.dateFormat]
  published = "2006-01-02"
  lastUpdated = "2006-01-02 15:04 MST"

[params.sidebar]
  emoji = "ğŸ“Š"
  subtitle = "åˆåŒä¼šç¤¾ãƒãƒ¼ãƒ†ãƒ¼ã‚·ãƒ§ãƒ³ï¼ãƒ¤ã‚¶ã‚­ãƒ¦ã‚¦ã‚¤ãƒã®æ´»å‹•ç´¹ä»‹ã‚µã‚¤ãƒˆã§ã™"
  description = "ãƒ‡ãƒ¼ã‚¿å¯è¦–åŒ–ã¯è¡¨ç¾ä¼é”ã¨èª²é¡Œè§£æ±ºã®äº¤å·®ç‚¹ã¨ã—ã¦ã€ä¸–ã®ä¸­ã«æ–°ã—ã„è¨˜æ³•ã‚’æä¾›ã—ã¾ã™ã€‚"

[params.sidebar.avatar]
  enabled = true
  local = true
  src = "img/avatar.png"

[params.sidebar.author]
    name = "çŸ¢å´è£•ä¸€ï¼Yuichi Yazaki"
    image = "img/avatar.png"
    bio = "æ ªå¼ä¼šç¤¾ãƒ“ã‚¸ãƒã‚¹ãƒ»ã‚¢ãƒ¼ã‚­ãƒ†ã‚¯ãƒ„ã«ã¦ãƒ¦ãƒ¼ã‚¶ãƒ¼ãƒ»ã‚¤ãƒ³ã‚¿ãƒ¼ãƒ•ã‚§ã‚¤ã‚¹ãƒ»ãƒ‡ã‚¶ã‚¤ãƒŠãƒ¼ãŠã‚ˆã³ã‚¢ãƒ¼ãƒˆãƒ»ãƒ‡ã‚£ãƒ¬ã‚¯ã‚¿ãƒ¼ã‚’7å¹´é–“çµŒé¨“å¾Œã€ç‹¬ç«‹ã€‚ä¼æ¥­ã‚„æ•™è‚²æ©Ÿé–¢ã§ã®è¬›ç¾©æ´»å‹•ã€ã‚¦ã‚§ãƒ–ã‚µã‚¤ãƒˆVisualizing.JPã«ãŠã‘ã‚‹æƒ…å ±ç™ºä¿¡ã€ã‚³ãƒŸãƒ¥ãƒ‹ãƒ†ã‚£Data Visualization Japanã«ãŠã‘ã‚‹ã‚³ãƒŸãƒ¥ãƒ‹ãƒ†ã‚£æ´»å‹•ãªã©ã€ãƒ‡ãƒ¼ã‚¿å¯è¦–åŒ–ã®å®Ÿè·µã¨æ™®åŠã«é–¢ã™ã‚‹ã•ã¾ã–ã¾ãªæ´»å‹•ã‚’ãŠã“ãªã£ã¦ã„ã‚‹ã€‚å…±è‘—æ›¸ã«ã€RESASã®æ•™ç§‘æ›¸ã€(æ—¥çµŒBPã€2016)ãŒã‚ã‚‹ã€‚åƒè‘‰å·¥æ¥­å¤§å­¦ãƒ‡ã‚¶ã‚¤ãƒ³ç§‘å­¦ä¿®å£«ä¿®äº†ã€‚ãƒ‡ãƒ¼ã‚¿ãƒ»ãƒ“ã‚¸ãƒ¥ã‚¢ãƒ©ã‚¤ã‚¼ãƒ¼ã‚·ãƒ§ãƒ³ãƒ»ã‚¸ãƒ£ãƒ‘ãƒ³ç™ºèµ·äºº/Yahoo!ãƒ‹ãƒ¥ãƒ¼ã‚¹ãƒ»ã‚¨ã‚­ã‚¹ãƒ‘ãƒ¼ãƒˆã€‚"

[params.article]
  math = false
  toc = true
  readingTime = true

[params.article.license]
  enabled = false
  default = ""

[params.comments]
  enabled = false
  provider = ""

[params.widgets]
  homepage = [
      { type = "search" },
      { type = "archives", params = { limit = 5 } },
      { type = "categories", params = { limit = 10 } },
      { type = "tag-cloud", params = { limit = 10 } }
  ]

[[params.widgets.page]]
  type = "toc"

[params.opengraph.twitter]
  site = "@visualizing_jp"
  card = "summary"

[params.defaultImage.opengraph]
  enabled = true
  local = true
  src = "img/avatar.png"

[params.colorScheme]
  toggle = false
  default = "dark"

[params.imageProcessing.cover]
  enabled = true

[params.imageProcessing.content]
  enabled = true

[pagination]
  pagerSize = 15

[menu]

[[menu.main]]
  identifier = "posts"
  name = "ãƒˆãƒƒãƒ—"
  url = "/"
  weight = 10

[[menu.main]]
  identifier = "about"
  name = "ãƒ¤ã‚¶ã‚­ãƒ¦ã‚¦ã‚¤ãƒã«ã¤ã„ã¦"
  url = "/about/"
  weight = 20

[[menu.main]]
  identifier = "lecture"
  name = "ç ”ä¿®"
  url = "/categories/lecture/"
  weight = 60

[[menu.main]]
  identifier = "talk"
  name = "è¬›æ¼”"
  url = "/categories/talk/"
  weight = 65

[[menu.main]]
  identifier = "education"
  name = "æ•™è‚²"
  url = "/categories/education/"
  weight = 70

[[menu.main]]
  identifier = "civictech"
  name = "ã‚·ãƒ“ãƒƒã‚¯ãƒ†ãƒƒã‚¯"
  url = "/categories/civictech/"
  weight = 90

[[menu.main]]
  identifier = "codefor"
  name = "Code for X"
  url = "/categories/codefor/"
  weight = 95

[[menu.main]]
  identifier = "journalism"
  name = "å ±é“"
  url = "/categories/journalism/"
  weight = 80

[related]
  includeNewer = true
  threshold = 60
  toLower = false

[[related.indices]]
  name = "tags"
  weight = 100

[[related.indices]]
  name = "categories"
  weight = 200

[markup.goldmark.renderer]
  unsafe = true

[markup.tableOfContents]
  endLevel = 4
  ordered = true
  startLevel = 2

[markup.highlight]
  noClasses = false
  codeFences = true
  guessSyntax = true
  lineNoStart = 1
  lineNos = true
  lineNumbersInTable = true
  tabWidth = 4
