[build]
  command = "hugo --gc --minify"
  publish = "public"

[build.environment]
  HUGO_VERSION = "0.152.0"
  HUGO_ENV = "production"
  HUGO_ENABLEGITINFO = "true"

[context.production]
  command = "hugo --gc --minify -b ${URL}"

[context.branch-deploy]
  command = "hugo --gc --minify -b ${DEPLOY_PRIME_URL}"

[context.deploy-preview]
  command = "hugo --gc --minify -b ${DEPLOY_PRIME_URL}"

[[plugins]]
  package = "netlify-plugin-hugo-cache-resources"
  [plugins.inputs]
    srcdir = "."

[[redirects]]
  from = "/"
  to = "/about/"
  status = 301
